### ISSUE TITLE
Direct3D9 Specification

### ISSUE THREAD

**Issue by Joshua-Ashton** [microsoft/DirectX-Specs#10]
Hi!

It'd be really cool if you could add the Direct3D9 spec on here. There's lots of undocumented and confusing behavior in d3d9 -- a sm1-3 specification would also be nice.

**Comment by shawnhar** [comment]
Unfortunately we don't have specs for earlier (<= D3D9 era) APIs in a form that could easily be published, so this isn't likely to be something we're ever able to add here.

The regular API documentation for D3D9 (https://docs.microsoft.com/en-us/windows/desktop/direct3d9/dx9-graphics) is the closest thing we have available.

Sorry!

**Comment by ValZapod** [comment]
"APIs in a form that could easily be published" Is it under NDA or what? I mean it is old as s***, what is the problem?

**Comment by ValZapod** [comment]
Concerning today's leak of all Windows XP, maybe at least add Directx 8?
