### ISSUE TITLE
 GPU Upload Heaps is not supported on RTX4080?

### ISSUE THREAD

**Issue by Vinluo** [microsoft/DirectX-Specs#124]
I can make sure Resizable-Bar Feature is enable on System Info through NVIDIA  Control Panel.
pDevice->CheckFeatureSupport(D3D12_FEATURE_D3D12_OPTIONS16, &options16, sizeof(options16) is still false.
GPU Driver is newest 531.61, that I just updated.
Is it not support right now？
Which GPUs GPUUploadHeapSupported？

**Comment by alexgong14** [comment]
This feature is only available in preview AgilitySDK, you probably want to use 1.710.0-preview. Also you'll need to enable developer mode.

**Comment by Vinluo** [comment]
I noticed these requirements and have configured and installed Agility SDK 1.710.0-preview. There is one thing I am not clear about, which is "developer mode." Does it refer to Windows' developer mode? If so, I should have correctly configured these environment settings.

**Comment by alexgong14** [comment]
Yes, this is referring to Windows developer mode, and I think you have correctly configured these settings. We'll investigate this issue and we will also ask Nvidia whether 531.61 supports GPU upload heaps.

**Comment by alexgong14** [comment]
@Vinluo Fyi, GPUUploadHeapSupported returns 
`(DriverSupportGPUUploadHeaps || UMA) && DeveloperModeEnabled`

In your case, since you are using a dGPU, what you need is `DriverSupportGPUUploadHeaps` + `DeveloperModeEnabled`. I just tested locally that `DeveloperModeEnabled` is working fine, and I've just reached out to Nvidia to ask if there are additional steps to enable GPU upload heap support other than enabling resizable bar. I'll let you know once there is an update.

**Comment by alexgong14** [comment]
I am assuming that your CheckFeatureSupport query is not failing but GPUUploadHeapSupported returns false. 

And here's an update: 531.61 supports GPU upload heaps. To enable ReBAR, you need to make sure ReBAR is enabled in the SBIOS and that the VBIOS on the GPU is updated (Ampere/RTX 30 series and higher, see “VBIOS Update” section in below link)  

You users can check with this to make sure ReBAR is working correctly [https://www.nvidia.com/en-us/geforce/news/geforce-rtx-30-series-resizable-bar-support/](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.nvidia.com%2Fen-us%2Fgeforce%2Fnews%2Fgeforce-rtx-30-series-resizable-bar-support%2F&data=05%7C01%7Calexgong%40microsoft.com%7C9d42d6056cd8427f604b08db3f5ba1c2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638173435261796545%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=yCPK23AW6PFWb6Rqq4EL96DgvqE1do2YkxEwgKaEiWY%3D&reserved=0)

**Comment by vdwtanner** [comment]
Closing as there hasn't been any update here in a while. Feel free to reopen if needed.
