### ISSUE TITLE
Geometry shader input primitive type - control point patch

### ISSUE THREAD

**Issue by gfxdev8** [microsoft/DirectX-Specs#134]
Seems not able to submit an issue to https://github.com/MicrosoftDocs/win32. Not sure here is the right place to go for this issue.

In the shader model 4.0 for geometry shader page, https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src/direct3dhlsl/dx-graphics-hlsl-geometry-shader.md, there is a primitive type **1-32 control point patch** in the **[Geometry Shader Input Primitves](https://github.com/MicrosoftDocs/win32/raw/docs/desktop-src/direct3dhlsl/images/d3d11-gsinputs1.png)** diagram. But the type does not exist in the primitive type table.
<html>
<body>

Primitive Type | Description
-- | --
point | Point list
line | Line list or line strip
triangle | Triangle list or triangle strip
lineadj | Line list with adjacency or line strip with adjacency
triangleadj | Triangle list with adjacency or triangle strip with adjacency

</body>
</html>

The question is how to use the control point patch type in the geometry shader.

**Comment by jenatali** [comment]
Looks like the correct name is "patchN", e.g. "patch1" for a 1-control-point patch.

**Comment by gfxdev8** [comment]
Thanks Jesse, I have found the answer in https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/sm5-object-inputpatch, it needs shader model 5.0 support.
