### ISSUE TITLE
Enhanced barrier spec: Mixing ..._BARRIER_ACCESS_... with ..._RESOURCE_STATE_...

### ISSUE THREAD

**Issue by GertyP** [microsoft/DirectX-Specs#169]
It looks like there's a mistake at the end of [Equivalent D3D12_BARRIER_ACCESS bit for each D3D12_RESOURCE_STATES bit](https://microsoft.github.io/DirectX-Specs/d3d/D3D12EnhancedBarriers.html#equivalent-d3d12_barrier_access-bit-for-each-d3d12_resource_states-bit) -
> Buffers and simultaneous-access textures can be freely accessed as all-but D3D12_BARRIER_ACCESS_DEPTH_STENCIL_WRITE|D3D12_BARRIER_ACCESS_DEPTH_STENCIL_READ|D3D12_RESOURCE_STATE_RAYTRACING_ACCELERATION_STRUCTURE.

since it's referring to 'access' but mixing `D3D12_BARRIER_ACCESS` and the old `D3D12_RESOURCE_STATES` enum values.  I'm guessing, instead of -
> ... |D3D12_RESOURCE_STATE_RAYTRACING_ACCELERATION_STRUCTURE

it should be something like -
> ... |D3D12_BARRIER_ACCESS_RAYTRACING_ACCELERATION_STRUCTURE_READ|D3D12_BARRIER_ACCESS_RAYTRACING_ACCELERATION_STRUCTURE_WRITE

**Comment by billkris-ms** [comment]
@GertyP, Yes, this is a typo and your suggested changes are correct. Will update shortly.
