### ISSUE TITLE
HLSL Shader Model 6.5 broken link

### ISSUE THREAD

**Issue by jenatali** [microsoft/DirectX-Specs#19]
The DXR 1.1 link is broken: https://microsoft.github.io/DirectX-Specs/d3d/HLSL_ShaderModel6_5.html#dxr-1.1.

**Comment by shawnhar** [comment]
That'll work once we publish the updated DXR spec (soon now)

This is what I get for pushing specs non atomically :-)

**Comment by jenatali** [comment]
The links *within* the DXR 1.1 section that point to the raytracing spec will work, but the link *to* the DXR 1.1 section of the SM6.5 spec is still broken.
