### ISSUE TITLE
VRS - Clarify SUM combiner

### ISSUE THREAD

**Issue by krawat10** [microsoft/DirectX-Specs#34]
The VRS documentation describes D3D12_SHADING_RATE_COMBINER_SUM in the following way:
"Apply cost B relative to A. C.xy = min(maxRate, A.xy + B.xy)
where maxRate is the largest permitted dimension of coarse pixel on the device."

I have created some cases with this combiner and got the following results:
- For A equal D3D12_SHADING_RATE_**4X4** and B equal D3D12_SHADING_RATE_**4X4** the result of SUM combining is D3D12_SHADING_RATE_**1X1**.
- For A equal D3D12_SHADING_RATE_**2X2** and B equal D3D12_SHADING_RATE_**2X2** the result of SUM combining is D3D12_SHADING_RATE_**4X4**.
- For A equal D3D12_SHADING_RATE_**1X1** and B equal D3D12_SHADING_RATE_**1X1** the result of SUM combining is D3D12_SHADING_RATE_**1X1**.

I still cannot understand how "SUM combiner" works. Can you describe it more precisely (maybe some example)?
https://github.com/microsoft/DirectX-Specs/blob/master/d3d/VariableRateShading.md#combining-shading-rate-factors

**Comment by shawnhar** [comment]
Hello, I'm curious why you closed this issue?  We were planning on investigating it on our end, so it would be helpful to know what you found...   Thanks!
