### ISSUE TITLE
typo in DepthBoundsTest.md

### ISSUE THREAD

**Issue by grafiks** [microsoft/DirectX-Specs#38]
DirectX-Specs/d3d/DepthBoundsTest.md

"We will add a CheckFeatureSupport query, e.g. **D3D12_FEATURE_D3D12_OPTIONS1**, to determine whether this feature is supported based on UMD version."

Should it be **D3D12_FEATURE_D3D12_OPTIONS2**? See https://docs.microsoft.com/en-us/windows/win32/api/d3d12/ns-d3d12-d3d12_feature_data_d3d12_options2

**Comment by shawnhar** [comment]
Good catch!  Care to send a pull request to correct this?

**Comment by grafiks** [comment]
Fixed with https://github.com/microsoft/DirectX-Specs/pull/39
