### ISSUE TITLE
8.1 support

### ISSUE THREAD

**Issue by lavanoid** [microsoft/DirectX-Specs#49]
I know this is isn't the best way to make a request, but I'm not sure what channels to go through in regards to bringing DX12 to Windows 8.1

Windows 7 is almost EOL and yet it has DX12 for select games but not 8.1. I use 8.1 on many of my machines as it's faster than 7, and it's still technically supported. Either I downgrade to 7 (which I'd rather not do, due to it being outdated) or upgrade to Windows 10 (which again, I'd rather not do as I cannot do a direct upgrade since I have a Mac Pro that requires me to patch the MBR to enable AHCI... so upgrading would likely break the installation/fail).

Are there any plans to bring DX12 to 8.1, rather than just 7? I know 8.1 has a smaller install base but there are still many people that use it for gaming, especially since it's lighter than Windows 10 so it plays nicer on older hardware.

**Comment by jenatali** [comment]
There are no plans to bring D3D12 to Windows 8.1 at this time, no.
