### ISSUE TITLE
Invalid image ref link in D3D12EnhancedBarriers.md

### ISSUE THREAD

**Issue by wqyvalinor** [microsoft/DirectX-Specs#85]
### Asymmetric Aliasing is Even More Expensive
![Figure 1](images/D3D12PipelineBarriers/AsymAliasing.png)

**Comment by vdwtanner** [comment]
Looks like this was resolved in https://github.com/microsoft/DirectX-Specs/commit/a47d4f8bb3b1dc8639fce31a98345bc947c45632
